
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 17 09:54:01 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 27;
  public static final int MENOS = 12;
  public static final int ELSE = 7;
  public static final int OR = 28;
  public static final int IGUAL = 20;
  public static final int THEN = 6;
  public static final int DECIMAL = 4;
  public static final int MENOR_IGUAL = 26;
  public static final int NOT = 29;
  public static final int SENTENCIA = 9;
  public static final int LLA_IZQ = 18;
  public static final int MAYOR_IGUAL = 25;
  public static final int MAYOR_QUE = 23;
  public static final int IF = 5;
  public static final int POT = 15;
  public static final int LLA_DER = 19;
  public static final int ID = 2;
  public static final int DIFERENTE2 = 22;
  public static final int MENOR_QUE = 24;
  public static final int EOF = 0;
  public static final int MULT = 13;
  public static final int DIFERENTE = 21;
  public static final int DIV = 14;
  public static final int PAR_IZQ = 16;
  public static final int error = 1;
  public static final int PAR_DER = 17;
  public static final int COND = 8;
  public static final int ENTERO = 3;
  public static final int ASIG = 10;
  public static final int MAS = 11;
}

